import "./globals.css";
import Header from "./_components/header/Header";
import Footer from "./_components/Footer/Footer";
import { AuthProvider } from "./context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <div className="layout">
            <Header></Header>
            <main> {children}</main>
            <Footer></Footer>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
