import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="layout">
          <Header></Header>
          <main> {children}</main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
